# Generated by Django 4.2.29 on 2026-04-03 21:17

from django.db import migrations
import pgvector.django.vector
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='page',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
