# Generated by Django 4.2.29 on 2026-04-04 15:13

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_page_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
