# Generated by Django 4.2.29 on 2026-04-04 17:01

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_page_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
