# Generated by Django 4.2.29 on 2026-04-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_page_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_helpful',
            field=models.BooleanField(default=False),
        ),
    ]
